apiVersion: v1
kind: Pod # 이 속성 값에 따라 spec 하위의 구성이 변화한다.
metadata:
  name: simple-echo # k8s Pod resource 의 이름
spec: # resource를 정의하기 위한 속성
  containers: # Pod 의 경우 Pod를 구성하는 containers를 정의한다.
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      env:
        - name: BACKEND_HOST # nginx는 proxing 대상이 될 BACKEND_HOST 값이 필요하다.
          value: localhost:8080
      ports:
        - containerPort: 8081
    - name: echo
      image: gihyodocker/echo:latest
      ports:
        - containerPort: 8080 # container가 노출할 port, docker image에서 EXPOSE 하고 있으면 안해도 된다.
